services:
  megatrans-mysql-dev:
    container_name: megatrans-mysql-dev
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: megatrans
      MYSQL_DATABASE: megatrans
      MYSQL_USER: megatrans
      MYSQL_PASSWORD: megatrans
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - megatrans-network-dev

  megatrans-app-dev:
    container_name: megatrans-app-dev
    depends_on:
      - megatrans-mysql-dev
    build:
      context: ../
    env_file:
      - .env.dev
    links:
      - megatrans-mysql-dev
    ports:
      - "3000:3000"
    restart: always
    networks:
      - megatrans-network-dev
    environment:
      VIRTUAL_HOST: megatrans.online,www.megatrans.online
      LETSENCRYPT_HOST: megatrans.online,www.megatrans.online
      LETSENCRYPT_EMAIL: it.jakub.wojtysiak@gmail.com

  megatrans-phpmyadmin-dev:
    container_name: megatrans-phpmyadmin-dev
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: megatrans-mysql-dev
      PMA_USER: root
      PMA_PASSWORD: megatrans
      UPLOAD_LIMIT: 100M
      MAX_EXECUTION_TIME: 300
      MEMORY_LIMIT: 512M
      POST_MAX_SIZE: 100M
      UPLOAD_MAX_FILESIZE: 100M
    depends_on:
      - megatrans-mysql-dev
    networks:
      - megatrans-network-dev

volumes:
  db-data:

networks:
  megatrans-network-dev:
    name: megatrans-network-dev
    driver: bridge
