services:
  # Inicjalizacja bazy danych
  megatrans-mysql-prod:
    container_name: megatrans-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - megatrans-mysql:/var/lib/mysql

  # Inicjalizacja Next JS
  megatrans-app-prod:
    container_name: megatrans-app-prod
    restart: always
    depends_on:
      - megatrans-mysql
    build:
      context: ../
    env_file:
      - .env.prod
    expose:
      - "3000"
    networks:
      - megatrans-network-prod
      - nginx-proxy
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: megatrans.online,www.megatrans.online
      LETSENCRYPT_HOST: megatrans.online,www.megatrans.online
      LETSENCRYPT_EMAIL: it.jakub.wojtysiak@gmail.com

volumes:
  megatrans-mysql:

networks:
  megatrans-network-prod:
    name: megatrans-network-prod
    driver: bridge
  nginx-proxy:
    external: true
